repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: ai/openai/v1
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: (?i).*testdata/
        exclude_types: [svg,mdx]
      - id: trailing-whitespace
        exclude_types: [svg,mdx]
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        exclude: ai/openai/v1
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: golangci-lint
      - id: go-mod-tidy
  - repo: https://github.com/pinglin/conventional-pre-commit
    rev: v1.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: generate-docs
        name: Generate Docs
        entry: bash -c 'make build-doc && make gen-doc'
        language: system
        files: \.(json|mdx)$
